version: "3"
services:
  sftp:
      image: atmoz/sftp
      volumes:
        - ./upload:/home/username
      ports:
        - "${SFTP_PORT}:22"
      env_file:
        - .env
      command: ${SFTP_USERNAME}:${SFTP_PASSWORD}:1001